# Generated by Django 6.0.7 on 2026-07-13 14:51

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_url',
            field=models.FileField(upload_to=apps.common.models.get_media_upload_path),
        ),
    ]
