# Generated by Django 6.0.7 on 2026-07-13 15:02

from django.db import migrations


def seed_media_categories(apps, schema_editor):
    MediaCategory = apps.get_model('common', 'MediaCategory')
    categories = [
        'Issue Media',
        'Before Repair',
        'After Repair',
        'Receipt',
        'Worker Photo',
        'Material Photo',
    ]
    for category in categories:
        MediaCategory.objects.get_or_create(category_name=category)

def remove_media_categories(apps, schema_editor):
    MediaCategory = apps.get_model('common', 'MediaCategory')
    categories = [
        'Issue Media',
        'Before Repair',
        'After Repair',
        'Receipt',
        'Worker Photo',
        'Material Photo',
    ]
    MediaCategory.objects.filter(category_name__in=categories).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_media_file_url'),
    ]

    operations = [
        migrations.RunPython(seed_media_categories, reverse_code=remove_media_categories),
    ]

