# Generated by Django 6.0.7 on 2026-07-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20260713_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_expense', 'Can view expense'), ('change_expense', 'Can change expense'), ('view_uploaded_by', 'Can view uploaded by'), ('change_uploaded_by', 'Can change uploaded by'), ('view_category', 'Can view category'), ('change_category', 'Can change category'), ('view_file_name', 'Can view file name'), ('change_file_name', 'Can change file name'), ('view_file_url', 'Can view file url'), ('change_file_url', 'Can change file url')]},
        ),
        migrations.AlterModelOptions(
            name='mediacategory',
            options={'permissions': [('view_category_name', 'Can view category name'), ('change_category_name', 'Can change category name')]},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('view_user', 'Can view user'), ('change_user', 'Can change user'), ('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_notification_type', 'Can view notification type'), ('change_notification_type', 'Can change notification type'), ('view_title', 'Can view title'), ('change_title', 'Can change title'), ('view_message', 'Can view message'), ('change_message', 'Can change message'), ('view_is_read', 'Can view is read'), ('change_is_read', 'Can change is read')]},
        ),
    ]
