# Generated by Django 5.2.7 on 2026-07-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_media_options_alter_mediacategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_uploaded_by', 'Can view uploaded by'), ('change_uploaded_by', 'Can change uploaded by'), ('view_category', 'Can view category'), ('change_category', 'Can change category'), ('view_file_name', 'Can view file name'), ('change_file_name', 'Can change file name'), ('view_file_url', 'Can view file url'), ('change_file_url', 'Can change file url')]},
        ),
        migrations.RemoveField(
            model_name='media',
            name='expense',
        ),
    ]
