# Generated by Django 5.2.7 on 2026-07-16 10:00

import django.db.models.deletion
from django.db import migrations, models


def populate_default_department(apps, schema_editor):
    Department = apps.get_model('stores', 'Department')
    MediaCategory = apps.get_model('common', 'MediaCategory')
    dept = Department.objects.filter(department_name="Maintenance").first()
    if not dept:
        dept = Department.objects.first()
    if not dept:
        dept = Department.objects.create(department_name="Maintenance")
    MediaCategory.objects.all().update(department=dept)

def reverse_populate_default_department(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_media_options_remove_media_expense'),
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacategory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_categories', to='stores.department'),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(populate_default_department, reverse_code=reverse_populate_default_department),
    ]
