# Generated by Django 5.2.7 on 2026-07-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_mediacategory_department_and_more'),
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacategory',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_categories', to='stores.department'),
        ),
        migrations.AddConstraint(
            model_name='mediacategory',
            constraint=models.UniqueConstraint(fields=('department', 'category_name'), name='unique_department_category_name'),
        ),
    ]
