# Generated by Django 5.2.7 on 2026-07-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_mediacategory_department_and_more'),
        ('finance', '0008_alter_expensetype_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='finance.expense'),
        ),
    ]
