# Generated by Django 5.2.7 on 2026-08-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
