# Generated by Django 5.2.7 on 2026-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
