# Generated by Django 6.0.7 on 2026-07-13 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('expense_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='maintenance.ticket')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensetype')),
            ],
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('reconciliation_id', models.AutoField(primary_key=True, serialize=False)),
                ('labour_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='maintenance.ticket')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
