# Generated by Django 6.0.7 on 2026-07-13 15:03

from django.db import migrations


def seed_expense_types(apps, schema_editor):
    ExpenseType = apps.get_model('finance', 'ExpenseType')
    types = [
        'Bus Fare',
        'Food',
        'Material',
    ]
    for type_name in types:
        ExpenseType.objects.get_or_create(expense_name=type_name)

def remove_expense_types(apps, schema_editor):
    ExpenseType = apps.get_model('finance', 'ExpenseType')
    types = [
        'Bus Fare',
        'Food',
        'Material',
    ]
    ExpenseType.objects.filter(expense_name__in=types).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_expense_types, reverse_code=remove_expense_types),
    ]

