# Generated by Django 6.0.7 on 2026-07-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20260713_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerate',
            options={'permissions': [('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_hourly_rate', 'Can view hourly rate'), ('change_hourly_rate', 'Can change hourly rate'), ('view_effective_from', 'Can view effective from'), ('change_effective_from', 'Can change effective from'), ('view_effective_to', 'Can view effective to'), ('change_effective_to', 'Can change effective to')]},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_expense_type', 'Can view expense type'), ('change_expense_type', 'Can change expense type'), ('view_amount', 'Can view amount'), ('change_amount', 'Can change amount'), ('view_expense_date', 'Can view expense date'), ('change_expense_date', 'Can change expense date'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks'), ('view_approved', 'Can view approved'), ('change_approved', 'Can change approved'), ('view_approved_by', 'Can view approved by'), ('change_approved_by', 'Can change approved by')]},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'permissions': [('view_expense_name', 'Can view expense name'), ('change_expense_name', 'Can change expense name')]},
        ),
        migrations.AlterModelOptions(
            name='reconciliation',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_verified_by', 'Can view verified by'), ('change_verified_by', 'Can change verified by'), ('view_labour_total', 'Can view labour total'), ('change_labour_total', 'Can change labour total'), ('view_expense_total', 'Can view expense total'), ('change_expense_total', 'Can change expense total'), ('view_material_total', 'Can view material total'), ('change_material_total', 'Can change material total'), ('view_grand_total', 'Can view grand total'), ('change_grand_total', 'Can change grand total'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks'), ('view_completed', 'Can view completed'), ('change_completed', 'Can change completed')]},
        ),
    ]
