# Generated by Django 5.2.7 on 2026-07-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_employeerate_options_alter_expense_options_and_more'),
        ('stores', '0006_store_phone_store_whatsapp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_expense_type', 'Can view expense type'), ('change_expense_type', 'Can change expense type'), ('view_amount', 'Can view amount'), ('change_amount', 'Can change amount'), ('view_expense_date', 'Can view expense date'), ('change_expense_date', 'Can change expense date'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks'), ('view_approved', 'Can view approved'), ('change_approved', 'Can change approved'), ('view_approved_by', 'Can view approved by'), ('change_approved_by', 'Can change approved by'), ('view_responsible_store', 'Can view responsible store'), ('change_responsible_store', 'Can change responsible store')]},
        ),
        migrations.AddField(
            model_name='expense',
            name='responsible_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='stores.store'),
        ),
    ]
