# Generated by Django 5.2.7 on 2026-07-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_media_options_remove_media_expense'),
        ('finance', '0004_alter_expense_options_expense_responsible_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_expense_type', 'Can view expense type'), ('change_expense_type', 'Can change expense type'), ('view_amount', 'Can view amount'), ('change_amount', 'Can change amount'), ('view_expense_date', 'Can view expense date'), ('change_expense_date', 'Can change expense date'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks'), ('view_receipt', 'Can view receipt'), ('change_receipt', 'Can change receipt'), ('view_approved', 'Can view approved'), ('change_approved', 'Can change approved'), ('view_approved_by', 'Can view approved by'), ('change_approved_by', 'Can change approved by'), ('view_responsible_store', 'Can view responsible store'), ('change_responsible_store', 'Can change responsible store')]},
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='common.media'),
        ),
    ]
