# Generated by Django 5.2.7 on 2026-07-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expense_options_expense_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetype',
            options={'permissions': [('view_expense_name', 'Can view expense name'), ('change_expense_name', 'Can change expense name'), ('view_parent', 'Can view parent'), ('change_parent', 'Can change parent')]},
        ),
        migrations.AddField(
            model_name='expensetype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_types', to='finance.expensetype'),
        ),
    ]
