# Generated by Django 5.2.7 on 2026-07-16 10:00

import django.db.models.deletion
from django.db import migrations, models


def populate_default_department(apps, schema_editor):
    Department = apps.get_model('stores', 'Department')
    ExpenseType = apps.get_model('finance', 'ExpenseType')
    dept = Department.objects.filter(department_name="Maintenance").first()
    if not dept:
        dept = Department.objects.first()
    if not dept:
        dept = Department.objects.create(department_name="Maintenance")
    ExpenseType.objects.all().update(department=dept)

def reverse_populate_default_department(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expensetype_options_expensetype_parent'),
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='stores.department'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='expense_name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(populate_default_department, reverse_code=reverse_populate_default_department),
    ]
