# Generated by Django 5.2.7 on 2026-07-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expensetype_department_and_more'),
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='stores.department'),
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(fields=('department', 'expense_name'), name='unique_department_expense_name'),
        ),
    ]
