# Generated by Django 5.2.7 on 2026-07-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expensetype_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='remarks',
        ),
    ]
