# Generated by Django 5.2.7 on 2026-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_expense_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt',
        ),
        migrations.AddField(
            model_name='expense',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
