# Generated by Django 5.2.7 on 2026-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_expense_receipt_expense_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
