# Generated by Django 5.2.7 on 2026-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_expensetype_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='approve_required',
            field=models.BooleanField(default=False),
        ),
    ]
