# Generated by Django 5.2.7 on 2026-09-20 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_expense_is_claimed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerclaim',
            options={'permissions': [('approve_workerclaim', 'Can approve worker claim'), ('reject_workerclaim', 'Can reject worker claim')]},
        ),
        migrations.AddField(
            model_name='expense',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerclaim',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resubmitted', 'Resubmitted'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('cleared_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ledgers', to=settings.AUTH_USER_MODEL)),
                ('claims', models.ManyToManyField(blank=True, related_name='ledgers', to='finance.workerclaim')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ledgers', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'permissions': [('process_ledger', 'Can mark ledger as processing'), ('clear_ledger', 'Can mark ledger as cleared'), ('reject_ledger', 'Can reject ledger')],
            },
        ),
    ]
