# Generated by Django 5.2.7 on 2026-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_workerclaim_options_expense_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
