# Generated by Django 6.1 on 2026-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_ledger_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerclaim',
            options={'permissions': [('approve_workerclaim', 'Can approve worker claim')]},
        ),
        migrations.RemoveField(
            model_name='workerclaim',
            name='reject_reason',
        ),
        migrations.AlterField(
            model_name='workerclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
