# Generated by Django 5.2.7 on 2026-09-21 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_profile_image'),
        ('finance', '0016_alter_workerclaim_options_and_more'),
        ('maintenance', '0048_alter_ticket_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workerclaim',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerclaim',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerclaim',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerclaim',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerclaim',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerclaim',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rework', 'Rework'), ('Paid', 'Paid')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerclaim',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_claims', to='maintenance.ticket'),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('Bundle', 'Bundle (WorkerClaim)'), ('Ledger', 'Ledger'), ('Expense', 'Expense')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('entity_type',), name='unique_active_workflow_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('is_final_step', models.BooleanField(default=False)),
                ('assigned_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='accounts.role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='finance.approvalworkflow')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rework', 'Rework'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bundles', models.ManyToManyField(blank=True, related_name='ledgers', to='finance.workerclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rework', 'Rework')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_actioned', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='finance.workerclaim')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_instances', to='finance.approvalstep')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='finance.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('ledger_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='finance.ledgergroup'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Check', 'Check'), ('Digital Wallet', 'Digital Wallet'), ('Other', 'Other')], default='Cash', max_length=30)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.workerclaim')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.expense')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.ledger')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'step_order'), name='unique_step_order_per_workflow'),
        ),
    ]
