# Generated by Django 5.2.7 on 2026-09-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_workerclaim_period_from_workerclaim_period_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalinstance',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='finance.expense'),
        ),
    ]
