# Generated by Django 5.2.7 on 2026-09-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_approvalinstance_expense'),
        ('stores', '0017_alter_store_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='ledgers', to='finance.expense'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='stores.store'),
        ),
    ]
