# Generated by Django 5.2.7 on 2026-09-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_ledger_expenses_ledger_store'),
        ('maintenance', '0048_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='maintenance.ticket'),
        ),
    ]
