# Generated by Django 6.1 on 2026-09-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_expense_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('approve_expense', 'Can approve expense'), ('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_expense_type', 'Can view expense type'), ('change_expense_type', 'Can change expense type'), ('view_amount', 'Can view amount'), ('change_amount', 'Can change amount'), ('view_expense_date', 'Can view expense date'), ('change_expense_date', 'Can change expense date'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks'), ('view_receipt', 'Can view receipt'), ('change_receipt', 'Can change receipt'), ('view_approved', 'Can view approved'), ('change_approved', 'Can change approved'), ('view_approved_by', 'Can view approved by'), ('change_approved_by', 'Can change approved by'), ('view_responsible_store', 'Can view responsible store'), ('change_responsible_store', 'Can change responsible store')]},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'permissions': [('approve_ledger', 'Can approve ledger')]},
        ),
    ]
