# Generated by Django 6.1 on 2026-09-30 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_profile_image'),
        ('finance', '0021_alter_expense_options_alter_ledger_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('approve_expense', 'Can approve expense'), ('reject_expense', 'Can reject expense'), ('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_expense_type', 'Can view expense type'), ('change_expense_type', 'Can change expense type'), ('view_amount', 'Can view amount'), ('change_amount', 'Can change amount'), ('view_expense_date', 'Can view expense date'), ('change_expense_date', 'Can change expense date'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks'), ('view_receipt', 'Can view receipt'), ('change_receipt', 'Can change receipt'), ('view_approved', 'Can view approved'), ('change_approved', 'Can change approved'), ('view_approved_by', 'Can view approved by'), ('change_approved_by', 'Can change approved by'), ('view_responsible_store', 'Can view responsible store'), ('change_responsible_store', 'Can change responsible store')]},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'permissions': [('approve_ledger', 'Can approve ledger'), ('reject_ledger', 'Can reject ledger')]},
        ),
        migrations.AlterModelOptions(
            name='workerclaim',
            options={'permissions': [('approve_workerclaim', 'Can approve worker claim'), ('reject_workerclaim', 'Can reject worker claim')]},
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to='accounts.role'),
        ),
    ]
