# Generated by Django 6.1 on 2026-10-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_alter_expense_options_alter_ledger_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerclaim',
            options={'permissions': [('create_bundle', 'Can create claim bundle'), ('edit_bundle', 'Can edit claim bundle'), ('submit_bundle', 'Can submit claim bundle for approval'), ('delete_bundle', 'Can delete claim bundle'), ('create_workerclaim', 'Can create worker claim'), ('edit_workerclaim', 'Can edit worker claim'), ('submit_workerclaim', 'Can submit worker claim for approval'), ('approve_workerclaim', 'Can approve worker claim'), ('reject_workerclaim', 'Can reject worker claim'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_total_claimed_amount', 'Can view total claimed amount'), ('change_total_claimed_amount', 'Can change total claimed amount'), ('view_status', 'Can view status'), ('change_status', 'Can change status'), ('view_period_from', 'Can view period from'), ('change_period_from', 'Can change period from'), ('view_period_to', 'Can view period to'), ('change_period_to', 'Can change period to'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks')]},
        ),
    ]
