# Generated by Django 6.1 on 2026-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_workerclaim_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rework', 'Rework'), ('Paid', 'Paid')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerclaim',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rework', 'Rework'), ('Paid', 'Paid')], default='Draft', max_length=20),
        ),
    ]
