# Generated by Django 6.1 on 2026-10-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_ledger_status_alter_workerclaim_status'),
        ('stores', '0017_alter_store_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_departments', models.ManyToManyField(blank=True, related_name='ledger_batches', to='stores.subdepartment')),
            ],
            options={
                'verbose_name': 'Ledger Batch',
                'verbose_name_plural': 'Ledger Batches',
                'ordering': ['batch_name'],
            },
        ),
    ]
