# Generated by Django 6.1 on 2026-10-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_ledgerbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='ledger_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='finance.ledgerbatch'),
        ),
    ]
