# Generated by Django 6.1 on 2026-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_ledgergroup_completed_at_ledgergroup_completed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgergroup',
            name='group_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
