# Generated by Django 6.0.7 on 2026-07-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('stores', '0002_subdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancenature',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_natures', to='stores.subdepartment'),
        ),
    ]
