# Generated by Django 6.0.7 on 2026-07-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancenature_sub_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_assigned_by', 'Can view assigned by'), ('change_assigned_by', 'Can change assigned by'), ('view_planned_hours', 'Can view planned hours'), ('change_planned_hours', 'Can change planned hours'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks')]},
        ),
        migrations.AlterModelOptions(
            name='maintenancenature',
            options={'permissions': [('view_nature_name', 'Can view nature name'), ('change_nature_name', 'Can change nature name'), ('view_department', 'Can view department'), ('change_department', 'Can change department'), ('view_sub_department', 'Can view sub department'), ('change_sub_department', 'Can change sub department'), ('view_default_priority', 'Can view default priority'), ('change_default_priority', 'Can change default priority'), ('view_active', 'Can view active'), ('change_active', 'Can change active')]},
        ),
        migrations.AlterModelOptions(
            name='natureworker',
            options={'permissions': [('view_nature', 'Can view nature'), ('change_nature', 'Can change nature'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker')]},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'permissions': [('view_priority_name', 'Can view priority name'), ('change_priority_name', 'Can change priority name'), ('view_level', 'Can view level'), ('change_level', 'Can change level')]},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'permissions': [('view_status_name', 'Can view status name'), ('change_status_name', 'Can change status name')]},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('view_work_order_no', 'Can view work order no'), ('change_work_order_no', 'Can change work order no'), ('view_store', 'Can view store'), ('change_store', 'Can change store'), ('view_department', 'Can view department'), ('change_department', 'Can change department'), ('view_nature', 'Can view nature'), ('change_nature', 'Can change nature'), ('view_priority', 'Can view priority'), ('change_priority', 'Can change priority'), ('view_status', 'Can view status'), ('change_status', 'Can change status'), ('view_title', 'Can view title'), ('change_title', 'Can change title'), ('view_description', 'Can view description'), ('change_description', 'Can change description'), ('view_created_by', 'Can view created by'), ('change_created_by', 'Can change created by'), ('view_approved_by', 'Can view approved by'), ('change_approved_by', 'Can change approved by'), ('view_approved_date', 'Can view approved date'), ('change_approved_date', 'Can change approved date'), ('view_rejected_by', 'Can view rejected by'), ('change_rejected_by', 'Can change rejected by'), ('view_rejected_date', 'Can view rejected date'), ('change_rejected_date', 'Can change rejected date'), ('view_reject_reason', 'Can view reject reason'), ('change_reject_reason', 'Can change reject reason'), ('view_closed_by', 'Can view closed by'), ('change_closed_by', 'Can change closed by'), ('view_closed_date', 'Can view closed date'), ('change_closed_date', 'Can change closed date')]},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_status', 'Can view status'), ('change_status', 'Can change status'), ('view_changed_by', 'Can view changed by'), ('change_changed_by', 'Can change changed by'), ('view_remarks', 'Can view remarks'), ('change_remarks', 'Can change remarks')]},
        ),
        migrations.AlterModelOptions(
            name='worklog',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_allocation', 'Can view allocation'), ('change_allocation', 'Can change allocation'), ('view_work_date', 'Can view work date'), ('change_work_date', 'Can change work date'), ('view_hours', 'Can view hours'), ('change_hours', 'Can change hours'), ('view_hourly_rate', 'Can view hourly rate'), ('change_hourly_rate', 'Can change hourly rate'), ('view_labour_amount', 'Can view labour amount'), ('change_labour_amount', 'Can change labour amount'), ('view_work_done', 'Can view work done'), ('change_work_done', 'Can change work done')]},
        ),
    ]
