# Generated by Django 5.2.7 on 2026-07-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_allocation_options_and_more'),
        ('stores', '0006_store_phone_store_whatsapp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancenature',
            options={'permissions': [('view_nature_name', 'Can view nature name'), ('change_nature_name', 'Can change nature name'), ('view_sub_department', 'Can view sub department'), ('change_sub_department', 'Can change sub department'), ('view_default_priority', 'Can view default priority'), ('change_default_priority', 'Can change default priority'), ('view_active', 'Can view active'), ('change_active', 'Can change active')]},
        ),
        migrations.RemoveField(
            model_name='maintenancenature',
            name='department',
        ),
        migrations.AlterField(
            model_name='maintenancenature',
            name='sub_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_natures', to='stores.subdepartment'),
        ),
    ]
