# Generated by Django 5.2.7 on 2026-07-16 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_ticket_options'),
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceNature',
            new_name='WorkNature',
        ),
        migrations.AlterModelOptions(
            name='worknature',
            options={'permissions': [('view_nature_name', 'Can view nature name'), ('change_nature_name', 'Can change nature name'), ('view_sub_department', 'Can view sub department'), ('change_sub_department', 'Can change sub department'), ('view_default_priority', 'Can view default priority'), ('change_default_priority', 'Can change default priority'), ('view_active', 'Can view active'), ('change_active', 'Can change active')]},
        ),
        migrations.AlterField(
            model_name='worknature',
            name='sub_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_natures', to='stores.subdepartment'),
        ),
    ]
