# Generated by Django 5.2.7 on 2026-07-16 10:00

import django.db.models.deletion
from django.db import migrations, models


def populate_default_department(apps, schema_editor):
    Department = apps.get_model('stores', 'Department')
    Priority = apps.get_model('maintenance', 'Priority')
    Status = apps.get_model('maintenance', 'Status')
    
    dept = Department.objects.filter(department_name="Maintenance").first()
    if not dept:
        dept = Department.objects.first()
    if not dept:
        dept = Department.objects.create(department_name="Maintenance")
        
    Priority.objects.all().update(department=dept)
    Status.objects.all().update(department=dept)

def reverse_populate_default_department(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_worknature_alter_natureworker_nature_and_more'),
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='stores.department'),
        ),
        migrations.AddField(
            model_name='status',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='stores.department'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(populate_default_department, reverse_code=reverse_populate_default_department),
    ]
