# Generated by Django 5.2.7 on 2026-07-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_priority_department_status_department_and_more'),
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='stores.department'),
        ),
        migrations.AlterField(
            model_name='status',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='stores.department'),
        ),
        migrations.AddConstraint(
            model_name='priority',
            constraint=models.UniqueConstraint(fields=('department', 'priority_name'), name='unique_department_priority_name'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('department', 'status_name'), name='unique_department_status_name'),
        ),
    ]
