# Generated by Django 5.2.7 on 2026-07-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_priority_department_alter_status_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknature',
            name='media_required',
            field=models.BooleanField(default=True),
        ),
    ]
