# Generated by Django 5.2.7 on 2026-07-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_ticket_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='status',
            name='unique_department_status_name',
        ),
        migrations.RemoveField(
            model_name='status',
            name='department',
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('status_name',), name='unique_department_status_name'),
        ),
    ]
