# Generated by Django 5.2.7 on 2026-07-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_remove_status_unique_department_status_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('view_work_order_no', 'Can view work order no'), ('change_work_order_no', 'Can change work order no'), ('view_store', 'Can view store'), ('change_store', 'Can change store'), ('view_department', 'Can view department'), ('change_department', 'Can change department'), ('view_nature', 'Can view nature'), ('change_nature', 'Can change nature'), ('view_priority', 'Can view priority'), ('change_priority', 'Can change priority'), ('view_status', 'Can view status'), ('change_status', 'Can change status'), ('view_title', 'Can view title'), ('change_title', 'Can change title'), ('view_description', 'Can view description'), ('change_description', 'Can change description'), ('view_created_by', 'Can view created by'), ('change_created_by', 'Can change created by'), ('view_approved_by', 'Can view approved by'), ('change_approved_by', 'Can change approved by'), ('view_approved_date', 'Can view approved date'), ('change_approved_date', 'Can change approved date'), ('view_rejected_by', 'Can view rejected by'), ('change_rejected_by', 'Can change rejected by'), ('view_rejected_date', 'Can view rejected date'), ('change_rejected_date', 'Can change rejected date'), ('view_reject_reason', 'Can view reject reason'), ('change_reject_reason', 'Can change reject reason'), ('view_closed_by', 'Can view closed by'), ('change_closed_by', 'Can change closed by'), ('view_closed_date', 'Can view closed date'), ('change_closed_date', 'Can change closed date'), ('create_ticket', 'Can create ticket'), ('approve_ticket', 'Can approve ticket'), ('reject_ticket', 'Can reject ticket'), ('complete_ticket', 'Can complete ticket'), ('view_all_department_tickets', 'Can view all department tickets'), ('create_ticket_all_departments', 'Can create ticket under all departments')]},
        ),
    ]
