# Generated by Django 5.2.7 on 2026-08-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order']},
        ),
        migrations.RemoveConstraint(
            model_name='status',
            name='unique_department_status_name',
        ),
        migrations.AddField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('status_name',), name='unique_status_name'),
        ),
    ]
