# Generated by Django 5.2.7 on 2026-08-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_statustransition'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusClearField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('field', 'Ticket Field'), ('relation', 'Related Model')], max_length=20)),
                ('target_name', models.CharField(help_text='Ticket field name or related accessor name.', max_length=100)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_from_status', to='maintenance.status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_to_status', to='maintenance.status')),
            ],
            options={
                'unique_together': {('from_status', 'to_status', 'target_type', 'target_name')},
            },
        ),
        migrations.CreateModel(
            name='StatusRequiredField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('field', 'Ticket Field'), ('relation', 'Related Model')], max_length=20)),
                ('target_name', models.CharField(help_text='Ticket field name or related accessor name.', max_length=100)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields', to='maintenance.status')),
            ],
            options={
                'unique_together': {('status', 'target_type', 'target_name')},
            },
        ),
        migrations.DeleteModel(
            name='StatusTransition',
        ),
    ]
