# Generated by Django 5.2.7 on 2026-08-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_statusclearfield_statusrequiredfield_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusrequiredfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='statusrequiredfield',
            name='optional_value',
            field=models.CharField(blank=True, help_text='Optional related field to check. Example: created_by.age', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='statusrequiredfield',
            unique_together={('status', 'target_type', 'target_name', 'optional_value')},
        ),
    ]
