# Generated by Django 5.2.7 on 2026-08-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_alter_statusrequiredfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusrequiredfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='statusrequiredfield',
            name='error_message',
            field=models.TextField(blank=True, help_text='Custom error message to display when this validation fails.', null=True, verbose_name='Error message'),
        ),
        migrations.AddField(
            model_name='statusrequiredfield',
            name='optional_key',
            field=models.CharField(blank=True, help_text='Optional related field/attribute name to check (e.g. role or username).', max_length=100, null=True, verbose_name='Optional key'),
        ),
        migrations.AlterField(
            model_name='statusrequiredfield',
            name='optional_value',
            field=models.CharField(blank=True, help_text='If provided, checks if the field/key value matches this value. If blank, checks for presence only.', max_length=255, null=True, verbose_name='Optional value'),
        ),
        migrations.AlterUniqueTogether(
            name='statusrequiredfield',
            unique_together={('status', 'target_type', 'target_name', 'optional_key', 'optional_value')},
        ),
    ]
