# Generated by Django 5.2.7 on 2026-08-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_alter_statusrequiredfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusrequiredfield',
            unique_together=None,
        ),
        migrations.AddField(
            model_name='statusrequiredfield',
            name='from_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_from_status', to='maintenance.status'),
        ),
        migrations.AddField(
            model_name='statusrequiredfield',
            name='option_value',
            field=models.CharField(blank=True, help_text='Match value for the field or optional key.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statusrequiredfield',
            name='to_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_to_status', to='maintenance.status'),
        ),
        migrations.AlterField(
            model_name='statusrequiredfield',
            name='error_message',
            field=models.CharField(blank=True, help_text='Custom error message returned if validation fails.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statusrequiredfield',
            name='optional_key',
            field=models.CharField(blank=True, help_text='Optional related field/key to check (e.g. username, store_name).', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='statusrequiredfield',
            name='optional_value',
        ),
        migrations.AlterUniqueTogether(
            name='statusrequiredfield',
            unique_together={('status', 'target_type', 'target_name', 'optional_key', 'option_value')},
        ),
    ]
