# Generated by Django 5.2.7 on 2026-08-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_alter_statusrequiredfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusrequiredfield',
            unique_together={('target_type', 'target_name', 'optional_key', 'option_value')},
        ),
        migrations.RemoveField(
            model_name='statusrequiredfield',
            name='status',
        ),
    ]
