# Generated by Django 5.2.7 on 2026-08-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_alter_statusrequiredfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusclearfield',
            name='success_message',
            field=models.CharField(blank=True, help_text='Optional message shown when this field is successfully cleared.', max_length=255, null=True),
        ),
    ]
