# Generated by Django 5.2.7 on 2026-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_statusclearfield_success_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusclearfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='statusclearfield',
            name='option_value',
            field=models.CharField(blank=True, help_text='Only clear this field when this value matches.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statusclearfield',
            name='optional_key',
            field=models.CharField(blank=True, help_text='Optional related field/key to check (e.g. username, store_name).', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='statusclearfield',
            unique_together={('from_status', 'to_status', 'target_type', 'target_name', 'optional_key', 'option_value')},
        ),
    ]
