# Generated by Django 5.2.7 on 2026-08-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_alter_statusclearfield_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusrequiredfield',
            old_name='error_message',
            new_name='message',
        ),
    ]
