# Generated by Django 5.2.7 on 2026-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_rename_error_message_statusrequiredfield_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrequiredfield',
            name='can_or_cant',
            field=models.CharField(choices=[('field', 'Ticket Field'), ('relation', 'Related Model')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
