# Generated by Django 5.2.7 on 2026-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_statusrequiredfield_can_or_cant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusclearfield',
            old_name='success_message',
            new_name='message',
        ),
        migrations.AddField(
            model_name='statusclearfield',
            name='can_or_cant',
            field=models.CharField(choices=[('field', 'Ticket Field'), ('relation', 'Related Model')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
