# Generated by Django 5.2.7 on 2026-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0026_rename_success_message_statusclearfield_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusclearfield',
            name='can_or_cant',
            field=models.CharField(choices=[('can', 'Can'), ('cant', "Can't")], max_length=20),
        ),
        migrations.AlterField(
            model_name='statusrequiredfield',
            name='can_or_cant',
            field=models.CharField(choices=[('can', 'Can'), ('cant', "Can't")], max_length=20),
        ),
    ]
