# Generated by Django 5.2.7 on 2026-08-06 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0028_alter_statusclearfield_can_or_cant_and_more'),
        ('stores', '0012_alter_store_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='age_days',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_approved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_closed_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_department', to='stores.department'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_nature', to='maintenance.worknature'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_priority', to='maintenance.priority'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_rejected_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_store', to='stores.store'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_status', to='maintenance.status'),
        ),
    ]
