# Generated by Django 5.2.7 on 2026-08-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0029_tickethistory_age_days_tickethistory_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusrequiredfield',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statusrequiredfield',
            name='from_status',
        ),
        migrations.RemoveField(
            model_name='statusrequiredfield',
            name='to_status',
        ),
        migrations.DeleteModel(
            name='StatusClearField',
        ),
        migrations.DeleteModel(
            name='StatusRequiredField',
        ),
    ]
