# Generated by Django 5.2.7 on 2026-08-06 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0030_alter_statusrequiredfield_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusClearField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('field', 'Ticket Field'), ('relation', 'Related Model')], max_length=20)),
                ('target_name', models.CharField(help_text='Ticket field name or related accessor name.', max_length=100)),
                ('optional_key', models.CharField(blank=True, help_text='Optional related field/key to check (e.g. username, store_name).', max_length=100, null=True)),
                ('option_value', models.CharField(blank=True, help_text='Only clear this field when this value matches.', max_length=255, null=True)),
                ('can_or_cant', models.CharField(choices=[('can', 'Can'), ('cant', "Can't")], default='can', max_length=20)),
                ('message', models.CharField(blank=True, help_text='Optional message shown when this field is successfully cleared.', max_length=255, null=True)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_from_status', to='maintenance.status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_to_status', to='maintenance.status')),
            ],
            options={
                'unique_together': {('from_status', 'to_status', 'target_type', 'target_name', 'optional_key', 'option_value')},
            },
        ),
        migrations.CreateModel(
            name='StatusRequiredField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('field', 'Ticket Field'), ('relation', 'Related Model')], max_length=20)),
                ('target_name', models.CharField(help_text='Ticket field name or related accessor name.', max_length=100)),
                ('optional_key', models.CharField(blank=True, help_text='Optional related field/key to check (e.g. username, store_name).', max_length=100, null=True)),
                ('option_value', models.CharField(blank=True, help_text='Match value for the field or optional key.', max_length=255, null=True)),
                ('can_or_cant', models.CharField(choices=[('can', 'Can'), ('cant', "Can't")], default='can', max_length=20)),
                ('message', models.CharField(blank=True, help_text='Custom error message returned if validation fails.', max_length=255, null=True)),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_from_status', to='maintenance.status')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_to_status', to='maintenance.status')),
            ],
            options={
                'unique_together': {('target_type', 'target_name', 'optional_key', 'option_value')},
            },
        ),
    ]
