# Generated by Django 5.2.7 on 2026-08-06 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0032_alter_statusrequiredfield_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('field', 'Field'), ('related', 'Related')], default='field', max_length=10)),
                ('path', models.CharField(help_text='Examples:\nstore.name\ncreated_by.username\nattachments.file_name\nallocations.name', max_length=255)),
                ('value', models.CharField(blank=True, help_text='Expected value.', max_length=255, null=True)),
                ('mode', models.CharField(choices=[('check', 'Check'), ('delete', 'Delete')], default='check', max_length=10)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rules', to='maintenance.status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rules', to='maintenance.status')),
            ],
            options={
                'db_table': 'status_change_rule',
            },
        ),
    ]
