# Generated by Django 5.2.7 on 2026-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0033_statuschangerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschangerule',
            name='message',
            field=models.TextField(help_text="For Check mode: error message displayed when validation fails.\nExample: 'Store must be assigned before closing.'\n\nFor Delete mode: describe what will be deleted.\nExample: 'Delete all attachments and allocations.'"),
        ),
        migrations.AlterField(
            model_name='statuschangerule',
            name='mode',
            field=models.CharField(choices=[('check', 'Check'), ('delete', 'Delete')], default='check', help_text='Check: validate before status change.\nDelete: remove related fields/records before status change.', max_length=10),
        ),
        migrations.AlterField(
            model_name='statuschangerule',
            name='path',
            field=models.CharField(help_text='Field/relationship path.\nExamples:\nstore.name\ncreated_by.username\nattachments.file_name\nallocations.name', max_length=255),
        ),
        migrations.AlterField(
            model_name='statuschangerule',
            name='value',
            field=models.CharField(blank=True, help_text='Expected value (used for check mode).', max_length=255, null=True),
        ),
    ]
