# Generated by Django 5.2.7 on 2026-08-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0034_alter_statuschangerule_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschangerule',
            name='message',
            field=models.TextField(blank=True, help_text="For Check mode: error message displayed when validation fails.\nExample: 'Store must be assigned before closing.'\n\nFor Delete mode: describe what will be deleted.\nExample: 'Delete all attachments and allocations.'", null=True),
        ),
        migrations.AlterField(
            model_name='statuschangerule',
            name='mode',
            field=models.CharField(choices=[('check', 'Check'), ('delete', 'Delete'), ('set', 'Set')], default='check', help_text='Check: validate before status change.\nDelete: remove related fields/records before status change.\nSet: set the field/relationship value to value before status change.', max_length=10),
        ),
        migrations.AlterField(
            model_name='statuschangerule',
            name='value',
            field=models.CharField(blank=True, help_text='Expected value (used for check and set modes).', max_length=255, null=True),
        ),
    ]
