# Generated by Django 5.2.7 on 2026-08-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0035_alter_statuschangerule_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschangerule',
            name='message',
            field=models.TextField(blank=True, help_text="For Check/Warning mode: error/warning message displayed when validation fails.\nExample: 'Store must be assigned before closing.'\n\nFor Delete mode: describe what will be deleted.\nExample: 'Delete all attachments and allocations.'", null=True),
        ),
        migrations.AlterField(
            model_name='statuschangerule',
            name='mode',
            field=models.CharField(choices=[('check', 'Check'), ('delete', 'Delete'), ('set', 'Set'), ('warning', 'Warning')], default='check', help_text='Check: validate before status change.\nDelete: remove related fields/records before status change.\nSet: set the field/relationship value to value before status change.\nWarning: warn if condition fails, but allow status change.', max_length=10),
        ),
        migrations.AlterField(
            model_name='statuschangerule',
            name='value',
            field=models.CharField(blank=True, help_text='Expected value (used for check, set, and warning modes).', max_length=255, null=True),
        ),
    ]
