# Generated by Django 5.2.7 on 2026-08-08 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0037_ticket_location_approval_ticket_location_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='location_approval',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='location_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_location_approved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='location_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='location_reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
