# Generated by Django 5.2.7 on 2026-08-08 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0038_tickethistory_location_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ticket_chats/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ticket_chats/videos/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='ticket_chats/voices/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='maintenance.ticket')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
