# Generated by Django 5.2.7 on 2026-08-16 12:53

import apps.maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0039_ticketchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.maintenance.models.get_chat_media_path),
        ),
        migrations.AlterField(
            model_name='ticketchatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.maintenance.models.get_chat_media_path),
        ),
        migrations.AlterField(
            model_name='ticketchatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to=apps.maintenance.models.get_chat_media_path),
        ),
    ]
