# Generated by Django 6.1 on 2026-08-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0041_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'permissions': [('view_priority_name', 'Can view priority name'), ('change_priority_name', 'Can change priority name'), ('view_level', 'Can view level'), ('change_level', 'Can change level'), ('can_call_worker', 'Can call worker'), ('can_call_store', 'Can call store')]},
        ),
    ]
