# Generated by Django 5.2.7 on 2026-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0043_alter_priority_options_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='allocation_voice_notes/'),
        ),
    ]
