# Generated by Django 5.2.7 on 2026-09-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_expense_is_claimed_and_more'),
        ('maintenance', '0046_alter_ticket_options_ticket_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='finance.workerclaim'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
