# Generated by Django 6.1 on 2026-10-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0048_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklog',
            options={'permissions': [('view_ticket', 'Can view ticket'), ('change_ticket', 'Can change ticket'), ('view_worker', 'Can view worker'), ('change_worker', 'Can change worker'), ('view_allocation', 'Can view allocation'), ('change_allocation', 'Can change allocation'), ('view_work_date', 'Can view work date'), ('change_work_date', 'Can change work date'), ('view_from_time', 'Can view from time'), ('change_from_time', 'Can change from time'), ('view_to_time', 'Can view to time'), ('change_to_time', 'Can change to time'), ('view_hours', 'Can view hours'), ('change_hours', 'Can change hours'), ('view_hourly_rate', 'Can view hourly rate'), ('change_hourly_rate', 'Can change hourly rate'), ('view_labour_amount', 'Can view labour amount'), ('change_labour_amount', 'Can change labour amount'), ('view_work_done', 'Can view work done'), ('change_work_done', 'Can change work done')]},
        ),
        migrations.AddField(
            model_name='worklog',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
