# Generated by Django 6.0.7 on 2026-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0002_subdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_departments',
            field=models.ManyToManyField(blank=True, related_name='users', to='stores.subdepartment'),
        ),
    ]
