# Generated by Django 6.0.7 on 2026-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_sub_departments'),
        ('stores', '0002_subdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accessible_stores',
            field=models.ManyToManyField(blank=True, related_name='accessible_users', to='stores.store'),
        ),
    ]
