# Generated by Django 6.0.7 on 2026-07-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_accessible_stores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_employee_no', 'Can view employee no'), ('change_employee_no', 'Can change employee no'), ('view_full_name', 'Can view full name'), ('change_full_name', 'Can change full name'), ('view_phone', 'Can view phone'), ('change_phone', 'Can change phone'), ('view_role', 'Can view role'), ('change_role', 'Can change role'), ('view_store', 'Can view store'), ('change_store', 'Can change store'), ('view_accessible_stores', 'Can view accessible stores'), ('change_accessible_stores', 'Can change accessible stores'), ('view_sub_departments', 'Can view sub departments'), ('change_sub_departments', 'Can change sub departments'), ('view_active', 'Can view active'), ('change_active', 'Can change active')]},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('view_role_name', 'Can view role name'), ('change_role_name', 'Can change role name')]},
        ),
    ]
