# Generated by Django 6.0.7 on 2026-07-14 08:10

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_employee_no', 'Can view employee no'), ('change_employee_no', 'Can change employee no'), ('view_full_name', 'Can view full name'), ('change_full_name', 'Can change full name'), ('view_phone', 'Can view phone'), ('change_phone', 'Can change phone'), ('view_whatsapp_number', 'Can view whatsapp number'), ('change_whatsapp_number', 'Can change whatsapp number'), ('view_profile_image', 'Can view profile image'), ('change_profile_image', 'Can change profile image'), ('view_role', 'Can view role'), ('change_role', 'Can change role'), ('view_store', 'Can view store'), ('change_store', 'Can change store'), ('view_accessible_stores', 'Can view accessible stores'), ('change_accessible_stores', 'Can change accessible stores'), ('view_sub_departments', 'Can view sub departments'), ('change_sub_departments', 'Can change sub departments'), ('view_active', 'Can view active'), ('change_active', 'Can change active')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.get_profile_image_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='WhatsApp number must be either 8 or 10 digits.', regex='^\\d{8}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits.', regex='^\\d{8}$')]),
        ),
    ]
