# Generated by Django 5.2.7 on 2026-07-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_whatsapplog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='store',
        ),
    ]
