# Generated by Django 5.2.7 on 2026-08-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_employee_no', 'Can view employee no'), ('change_employee_no', 'Can change employee no'), ('view_full_name', 'Can view full name'), ('change_full_name', 'Can change full name'), ('view_phone', 'Can view phone'), ('change_phone', 'Can change phone'), ('view_whatsapp_number', 'Can view whatsapp number'), ('change_whatsapp_number', 'Can change whatsapp number'), ('view_profile_image', 'Can view profile image'), ('change_profile_image', 'Can change profile image'), ('view_role', 'Can view role'), ('change_role', 'Can change role'), ('view_store', 'Can view store'), ('change_store', 'Can change store'), ('view_accessible_stores', 'Can view accessible stores'), ('change_accessible_stores', 'Can change accessible stores'), ('view_sub_departments', 'Can view sub departments'), ('change_sub_departments', 'Can change sub departments'), ('view_active', 'Can view active'), ('change_active', 'Can change active'), ('can_edit_full_manager_details', 'Can edit full manager details'), ('can_edit_half_manager_details', 'Can edit half manager details')]},
        ),
    ]
