# Generated by Django 5.2.7 on 2026-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
