# Generated by Django 5.2.7 on 2026-08-29 11:43

import apps.accounts.models
import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.get_profile_image_path, validators=[apps.accounts.validators.validate_profile_image_is_human]),
        ),
    ]
