# Generated by Django 6.1 on 2026-08-29 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Report title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Report description')),
                ('data_source', models.CharField(help_text='Registry key, e.g. maintenance.ticket', max_length=100)),
                ('definition', models.JSONField(default=dict, help_text='Full report config: columns, filters, sorting, grouping, aggregations, formatting, layout')),
                ('theme', models.CharField(choices=[('corporate_blue', 'Corporate Blue'), ('maintenance', 'Maintenance'), ('finance', 'Finance'), ('minimal', 'Minimal'), ('executive', 'Executive')], default='corporate_blue', help_text='Visual theme for rendered output', max_length=30)),
                ('page_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=15)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter')], default='A4', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='If True, all authorized users can access this report')),
                ('shared_roles', models.JSONField(blank=True, default=None, help_text='List of role names that can access this report', null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Definition',
                'verbose_name_plural': 'Report Definitions',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportGenerationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(default='Ad-hoc Report', help_text='Snapshot of report name at generation time', max_length=255)),
                ('data_source', models.CharField(default='', max_length=100)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('export_format', models.CharField(choices=[('preview', 'Preview'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('filters_used', models.JSONField(default=dict, help_text='Snapshot of runtime filters applied')),
                ('definition_snapshot', models.JSONField(default=dict, help_text='Snapshot of the full report definition used')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_logs', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, help_text='NULL for ad-hoc (unsaved) report runs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='reports.reportdefinition')),
            ],
            options={
                'verbose_name': 'Report Generation Log',
                'verbose_name_plural': 'Report Generation Logs',
                'ordering': ['-generated_date'],
            },
        ),
    ]
