# Generated by Django 6.1 on 2026-08-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdefinition',
            options={'ordering': ['-updated_date'], 'permissions': [('can_generate_report', 'Can generate report')], 'verbose_name': 'Report Definition', 'verbose_name_plural': 'Report Definitions'},
        ),
    ]
