# Generated by Django 6.0.7 on 2026-07-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('sub_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_department_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='stores.department')),
            ],
        ),
    ]
