# Generated by Django 6.0.7 on 2026-07-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_subdepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('view_department_name', 'Can view department name'), ('change_department_name', 'Can change department name')]},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'permissions': [('view_store_name', 'Can view store name'), ('change_store_name', 'Can change store name'), ('view_address', 'Can view address'), ('change_address', 'Can change address'), ('view_phone', 'Can view phone'), ('change_phone', 'Can change phone'), ('view_manager_name', 'Can view manager name'), ('change_manager_name', 'Can change manager name'), ('view_active', 'Can view active'), ('change_active', 'Can change active')]},
        ),
        migrations.AlterModelOptions(
            name='subdepartment',
            options={'permissions': [('view_department', 'Can view department'), ('change_department', 'Can change department'), ('view_sub_department_name', 'Can view sub department name'), ('change_sub_department_name', 'Can change sub department name')]},
        ),
    ]
