# Generated by Django 5.2.7 on 2026-07-14 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_department_options_alter_store_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subdepartment',
            options={},
        ),
        migrations.RemoveField(
            model_name='store',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.AddField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
