# Generated by Django 5.2.7 on 2026-07-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_department_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='manager',
        ),
    ]
