# Generated by Django 5.2.7 on 2026-07-14 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_store_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits.', regex='^\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='WhatsApp number must be either 8 or 10 digits.', regex='^\\d{8}$|^\\d{10}$')]),
        ),
    ]
