# Generated by Django 6.0.7 on 2026-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
