# Generated by Django 5.2.7 on 2026-07-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_area_store_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(max_length=20),
        ),
    ]
