# Generated by Django 5.2.7 on 2026-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_store_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.CharField(blank=True, choices=[('SUPER_MARKET', 'Super Market'), ('HYPER_MARKET', 'Hyper Market'), ('WAREHOUSE', 'Warehouse'), ('FRESH', 'Fresh'), ('COSTO', 'Costo')], max_length=20, null=True),
        ),
    ]
