# Generated by Django 5.2.7 on 2026-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_alter_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
