# Generated by Django 6.1 on 2026-09-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_department_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(blank=True, choices=[('SUPER_MARKET', 'Super Market'), ('HYPER_MARKET', 'Hyper Market'), ('WAREHOUSE', 'Warehouse'), ('FRESH', 'Fresh'), ('COSTO', 'Costo'), ('CAMP', 'Camp'), ('KITCHEN', 'Kitchen'), ('ROASTERY', 'Roastery'), ('FINE DINE', 'Fine Dine')], max_length=20, null=True),
        ),
    ]
