# Generated by Django 5.2.7 on 2026-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='short_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
