# Generated by Django 6.1 on 2026-10-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_alter_store_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='location_approval_throttle',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Default Location Approval throttle limit for this department (default: 5). If 0 or null, throttling is disabled.', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location_approval_throttle',
            field=models.PositiveIntegerField(blank=True, help_text='Custom Location Approval throttle limit for this store across departments (overrides department default if set)', null=True),
        ),
        migrations.CreateModel(
            name='StoreDepartmentThrottle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('throttle_limit', models.PositiveIntegerField(help_text='Custom Location Approval throttle limit for this specific store and department')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_throttles', to='stores.department')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_throttles', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Department Throttle',
                'verbose_name_plural': 'Store Department Throttles',
                'unique_together': {('store', 'department')},
            },
        ),
    ]
